targets:
  $default:
    builders:
      flutter_output|resource_metadata_other:
        enabled: true
    sources:
      exclude:
        - lib/features/app_home/i_home_service_impl.dart #build:app_home ----> not work
        - lib/features/app_home/** #build:app_home ----> not work

builders:
  resource_metadata_other:
    import: "package:flutter_output/features_core/com/module/service/annotation/builder.dart"
    builder_factories: ["serviceBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: root_package
    build_to: source
#    build_to: cache
#    applies_builders: ["source_gen|combining_builder"]